server:
  port: 8099


spring:
  thymeleaf:
    suffix: .html

  freemarker:
    suffix: .ftl

  datasource:
    url:  "jdbc:mysql://localhost:3306/guest"
    password: 123456
    username: root

mybatis:

  #mapper-locations: classpath*:/mybatis/mapper/*.xml
  #type-aliases-package: com.renhe.model
#config-location: classpath:mybatis-config.xml