server:
  port: 8090

spring:
  thymeleaf:
    suffix: .html

  freemarker:
    suffix: ftl

  datasource:
    url:  "jdbc:mysql://localhost:3306/guest"
    password: 123456
    username: root


  jpa:
    #自动创建、更新、验证表结构
    hibernate:
      ddl-auto: update
    #设置数据库引擎为InnoDB
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #打印sql语句，方便调试
    show-sql: true